hg_38_bwa_index: "/sci/data/reference_data/Homo_sapiens/Ensembl/GRCh38/Sequence/BWAIndex/genome.fa"

enhancers_to_count:
  bed: "Analysis/enhancers/tcea_FANTOM/tcea_FANTOM_filtered_enhancers.bed"
  gtf: "Analysis/enhancers/tcea_FANTOM/tcea_FANTOM_filtered_enhancers.gtf"
  metadata: "Analysis/enhancers/tcea_FANTOM/tcea_FANTOM_enhancers_metadata.txt"

lib_size_normalize: "gex" # options: "erna" or "gex" or "none"

erna_len_normalize: false  # whether to length normalize erna counts