executor: "slurm"

default-resources:
    mem_mb: 2000
    runtime: 15  # in minutes
    cpus: 1

set-resources:
    test:
        mem_mb: 2000
        time_min: 15
    snare_01_download_fastq:
        mem_mb: 12000
        runtime: 15  # in minutes
        cpus: 1
    snare_03_alignment:
        mem_mb: 30000
        runtime: 60  # in minutes
        cpus: 1
        cpus_per_task: 8
    snare_05_call_peaks:
        mem_mb: 16000
        runtime: 20  # in minutes
    snare_10_count_each_cell:
        mem_mb: 16000
        runtime: 30  # in minutes
    snare_13_counts_analysis:
        mem_mb: 16000
        runtime: 10  # in minutes
    snare_bwa_align:
        mem_mb: 64000
        runtime: 180  # in minutes
        cpus: 1
        cpus_per_task: 4
    snare_bwa_assign_to_genes:
        mem_mb: 32000
        runtime: 60  # in minutes
        cpus: 1
        cpus_per_task: 4
    snare_bwa_count_per_cell:
        mem_mb: 32000
        runtime: 25  # in minutes
    snare_count_by_atac_download_fastq:
        mem_mb: 12000
        runtime: 60  # in minutes
        cpus: 1
    PBMC_10X_02_download_fastq:
        mem_mb: 8000
        runtime: 720  # in minutes
    PBMC_10X_03_check_md5sum:
        mem_mb: 8000
        runtime: 60  # in minutes
    PBMC_10X_04_untar_fastq:
        mem_mb: 8000
        runtime: 60  # in minutes
    PBMC_10X_extract:
        mem_mb: 16000
        runtime: 150  # in minutes
        cpus_per_task: 8
    PBMC_10X_align:
        mem_mb: 64000
        runtime: 360  # in minutes
        cpus: 1
        cpus_per_task: 8
    PBMC_10X_assign_to_genes:
        mem_mb: 64000
        runtime: 360  # in minutes
        cpus: 1
        cpus_per_task: 8
    PBMC_10X_sort_index:
        mem_mb: 71680
        runtime: 120  # in minutes
        cpus_per_task: 8
    PBMC_10X_count_per_cell:
        mem_mb: 64000
        runtime: 240  # in minutes
    PBMC_10X_ATAC_extract_lane:
        mem_mb: 16000
        runtime: 480  # in minutes
    PBMC_10X_ATAC_filter_barcodes:
        mem_mb: 16000
        runtime: 480  # in minutes
    PBMC_10X_ATAC_count_fragments:
        mem_mb: 64000
        runtime: 480  # in minutes
        cpus: 1
        cpus_per_task: 12
    PBMC_10X_erna_preprocess:
        mem_mb: 45000
        runtime: 5  # in minutes

    

seconds-between-status-checks: 2
max-status-checks-per-second: 1
jobs: 8
keep-incomplete: true
use-conda: true
slurm-init-seconds-before-status-checks: 5